language: cpp

compiler:
  - g++
  - clang++

matrix:
  include:
    - os: linux
    - os: osx

before_install:
  - eval "${MATRIX_EVAL}"

script:
  - cmake -H. -Bbuild -DCMAKE_VERBOSE_MAKEFILE=ON
  - cmake --build build

